[package]
name = "animation"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { path = "../app" }
essential = { path = "../essential" }
ecs = { path = "../ecs" }
glam = { version = "0.30.1" }
uuid = { version = "1.18.1", features = ["v4"] }
petgraph = { version = "0.8" }
log = "0.4.27"
